/**
 * Finding — the shared data contract across all Sentinel engines.
 *
 * All three engines (Web, MCP, Code) produce findings in this shape.
 * This is the single most important shared type in the platform —
 * it's what makes unified reporting, correlation, and scoring possible
 * without coupling the engines' internals.
 *
 * Defined by: INSTRUCTION.md Section 8, Architecture Spec Section 6.
 *
 * CodeSentinel uses this shape for its --export output.
 * Web and MCP engines write this shape directly to the shared Finding table.
 * The aggregator reads this shape to correlate findings across engines.
 */

import type { Severity, Confidence, EngineType } from './types.js';

/**
 * Structured AI assessment for a low-confidence finding.
 * Contains the AI's verdict, reasoning, and suggested remediation,
 * cleanly separated from the deterministic engine's output.
 */
export interface AiAssessment {
  verdict: 'confirmed' | 'likely' | 'uncertain' | 'dismissed';
  confidence: number;
  reason: string;
  impact?: string;
  remediation?: string;
  additionalEvidenceNeeded?: string[];
  patch?: string;
  poc?: string;
}

/**
 * A single finding produced by any Sentinel engine.
 *
 * Every finding must answer four questions:
 *   WHAT happened, WHERE it happened, WHY it matters, HOW to fix it.
 *
 * Evidence must never contain secrets (API keys, tokens, passwords).
 * Redact sensitive data before writing evidence.
 */
export interface Finding {
  /** Unique identifier for this finding. */
  id: string;

  /** Project this finding belongs to. */
  projectId: string;

  /**
   * TestRun this finding is associated with.
   * Null for CodeSentinel imports — they are tied to a CodeScanImport
   * record, not a live TestRun.
   */
  runId: string | null;

  /**
   * Which engine produced this finding.
   *
   * Note: INSTRUCTION.md Section 8 uses "engine", Architecture Spec
   * Section 6 uses "engineType". We follow the explicit TypeScript
   * interface from INSTRUCTION.md.
   */
  engine: EngineType;

  /** Identifier for the detection rule that produced this finding. */
  ruleId: string;

  /**
   * Category grouping for this finding.
   * Examples: "security-headers", "broken-links", "api-integration",
   *           "schema-rigor", "privilege-analysis", "type-error".
   */
  category: string;

  /** Severity of the finding. */
  severity: Severity;

  /**
   * Confidence level of the detection.
   * Low-confidence findings are eligible for optional AI-assisted triage.
   */
  confidence: Confidence;

  /** Short, human-readable title summarizing the finding. */
  title: string;

  /**
   * Detailed explanation of what was found.
   * Should be specific and mechanical, not vague.
   * Good: "fetch() is called without checking response.ok"
   * Bad:  "This code looks unsafe"
   */
  message: string;

  /**
   * Where the finding was detected.
   * - Web engine: URL or page path (e.g., "https://example.com/login")
   * - MCP engine: tool name (e.g., "filesystem_write")
   * - Code engine: file:line (e.g., "src/api/client.ts:42")
   */
  location?: string;

  /**
   * Structured evidence supporting the finding.
   * Must NOT contain secrets (API keys, tokens, passwords, credentials).
   */
  evidence: Record<string, unknown>;

  /** Actionable remediation guidance. */
  remediation: string;

  /**
   * Links a correlated finding across engines.
   * Examples:
   * - Web finding linked to the MCP finding it triggered discovery of
   * - Code finding linked to the Web finding showing API drift
   *
   * Set explicitly by the aggregator, never inferred silently.
   * A drift finding (Code vs. Web) must only be created when both
   * a Code Engine import and a Web Engine run exist for the same project.
   */
  relatedFindingId?: string;

  /** ISO 8601 timestamp of when this finding was created. */
  timestamp: string;

  /**
   * Optional AI assessment for this finding.
   * Set by the AI Reviewer for eligible low-confidence findings.
   */
  aiAssessment?: AiAssessment;

  /**
   * Optional plain-language narrative for this finding.
   * Written by the optional AI Narrator; strictly advisory — it never
   * changes severity, confidence, or any deterministic field.
   */
  narrative?: FindingNarrative;
}

/**
 * A human-readable explanation of a finding, generated by the optional
 * AI Narrator. Every field answers a question a non-security reader asks:
 * what is this, how would it hurt us, and what do we do about it.
 */
export interface FindingNarrative {
  /** One-paragraph explanation in plain language, no jargon. */
  plainExplanation: string;

  /** A concrete, realistic story of how this could be exploited here. */
  attackerScenario: string;

  /** The practical business consequence if exploited. */
  businessImpact: string;

  /** Ordered, concrete steps to fix the issue. */
  fixSteps: string[];
}

/**
 * A themed chapter grouping related findings in an audit report,
 * produced by the optional AI Narrator so reports read like a
 * consultant's audit instead of a flat list.
 */
export interface AuditChapter {
  /** Human chapter title, e.g. "Your authentication layer". */
  title: string;

  /** Short intro paragraph explaining the theme in plain language. */
  intro: string;

  /** IDs of findings belonging to this chapter. Guardrail-checked. */
  findingIds: string[];
}
